const $=id=>document.getElementById(id);
let state,drag=null,selected=new Set(),active=null,project=null,tab='General',extraRows=0,previewCell=1,packages=new Map();
const portraits={Luigi:'Luigi.png',Mario:'Mario.png',Donkey:'Donkey.png',Link:'Link.png',Samus:'Samus.png',Captain:'Captain.png',Ness:'Ness.png',Yoshi:'Yoshi.png',Kirby:'Kirby.png',Fox:'Fox.png',Pikachu:'Pikachu.png',Purin:'Purin.png'};
for(let n=3;n<=12;n++)$('columns').add(new Option(n,n));
function message(s){$('status').textContent=s}
async function post(url,data){const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const out=await response.json();if(!response.ok)throw Error(out.error);return out}
async function busy(button,fn){button.disabled=true;document.body.classList.add('busy');try{await fn()}catch(e){message(e.message)}finally{button.disabled=false;document.body.classList.remove('busy')}}
function normalize(){state.characters.forEach((c,i)=>{if(c.cell===undefined)c.cell=i;if(!c.builtin)packages.set(c.id,c)})}
function freeCell(){const occupied=new Set(state.characters.filter(c=>c.enabled!==false).map(c=>c.cell));let cell=0;while(occupied.has(cell))cell++;if(cell>=120)throw Error('The roster has reached 120 cells');return cell}
function merge(c){const old=state.characters.find(x=>x.id===c.id);if(old){const cell=old.cell;Object.assign(old,c,{cell})}else state.characters.push({...c,cell:freeCell()});packages.set(c.id,c)}
function draw(){normalize();const enabled=state.characters.filter(c=>c.enabled!==false);$('columns').value=state.columns;$('count').textContent=`${enabled.length} fighters · ${selected.size} selected`;const grid=$('roster');grid.replaceChildren();grid.style.gridTemplateColumns=`repeat(${state.columns},minmax(0,1fr))`;let rows=Math.ceil((Math.max(0,...enabled.map(c=>c.cell))+1)/state.columns)+extraRows;rows=Math.min(Math.ceil(120/state.columns),Math.max(2,rows));
for(let cell=0;cell<Math.min(120,rows*state.columns);cell++){let c=enabled.find(c=>c.cell===cell),el=document.createElement('div');el.className='cell'+(c?' filled':'')+(c&&selected.has(c.id)?' selected':'');el.ondragover=e=>e.preventDefault();el.ondrop=e=>{e.preventDefault();const moving=state.characters.find(c=>c.id===drag);if(!moving)return;const previous=moving.cell;moving.cell=cell;if(c)c.cell=previous;drag=null;draw()};if(!c){el.textContent=`${Math.floor(cell/state.columns)+1} · ${cell%state.columns+1}`;grid.append(el);continue}el.draggable=true;el.ondragstart=()=>drag=c.id;el.onclick=()=>{previewCell=cell};let check=document.createElement('input');check.type='checkbox';check.setAttribute('aria-label',`Select ${c.name}`);check.checked=selected.has(c.id);check.onchange=()=>{if(check.checked)selected.add(c.id);else selected.delete(c.id);draw()};let img=document.createElement('img');img.src='/assets/'+(c.portrait||'textures/MNPlayersPortraits/'+portraits[c.base]);img.alt=c.name;let title=document.createElement('strong');title.textContent=c.name;el.append(check,img,title);if(!c.builtin){let button=document.createElement('button');button.textContent='Edit project';button.onclick=()=>openProject(c);el.append(button)}grid.append(el)}
$('packages').replaceChildren();for(const c of packages.values()){const row=document.createElement('div');row.className='toolbar';const name=document.createElement('span');name.textContent=c.name;name.style.flex=1;const button=document.createElement('button');button.textContent=state.characters.some(x=>x.id===c.id)?'Edit':'Add to roster';button.onclick=()=>{if(state.characters.some(x=>x.id===c.id))openProject(c);else{merge({...c,enabled:true});draw()}};row.append(name,button);$('packages').append(row)}}
$('columns').onchange=()=>{state.columns=+$('columns').value;extraRows=0;draw()};$('addrow').onclick=()=>{extraRows++;draw()};$('compact').onclick=()=>{state.characters.filter(c=>c.enabled!==false).forEach((c,i)=>c.cell=i);extraRows=0;draw()};$('selectall').onclick=()=>{selected=new Set(state.characters.map(c=>c.id));draw()};$('remove').onclick=()=>{if(selected.size===state.characters.length)return message('Keep at least one fighter in the roster.');state.characters=state.characters.filter(c=>!selected.has(c.id));selected.clear();draw();message('Slots removed. Save the roster to apply the layout.')};
$('save').onclick=()=>busy($('save'),async()=>{await post('/api/roster',state);message('Roster saved. Reopen character select to load this layout.')});
$('importpath').onclick=()=>busy($('importpath'),async()=>{message('Importing source projects and converting models…');const result=await post('/api/import-directory',{path:$('path').value});for(const c of result.characters)merge(c);draw();message(`${result.characters.length} project(s) imported. Save the roster to apply.\n`+result.errors.map(e=>`${e.project}: ${e.error}`).join('\n'))});
$('upload').onclick=()=>busy($('upload'),async()=>{message('Uploading source projects…');const files=await Promise.all([...$('files').files].filter(f=>!f.webkitRelativePath.split('/').some(p=>['StellarExport','converted','.git'].includes(p))).map(f=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve({name:f.webkitRelativePath||f.name,data:r.result.split(',')[1]});r.onerror=reject;r.readAsDataURL(f)})));const result=await post('/api/upload-directory',{files});for(const c of result.characters)merge(c);draw();message(`${result.characters.length} project(s) imported.\n`+result.errors.map(e=>e.error).join('\n'))});
const sections={General:null,'Bone mapping':'bone_mappings',Animations:'animations',Hitboxes:'hitboxes',Physics:'stats',Sounds:'sounds',Stages:'stages',Controls:'input_bindings','Project JSON':'raw'};
async function openProject(c){try{const response=await fetch('/api/project?id='+encodeURIComponent(c.id));const out=await response.json();if(!response.ok)throw Error(out.error);active=c;project=out;tab='General';$('projecttitle').textContent=c.name+' · Source project';$('projectnote').textContent='Edit and save authoring data here. Convert model applies bone mappings and model settings to Sagas; animation, hitbox, sound and stage overrides remain authoring data until their runtime adapters are added.';$('saveproject').disabled=$('buildproject').disabled=false;drawEditor();$('projecttitle').scrollIntoView({behavior:'smooth'})}catch(e){message(e.message)}}
function inputFor(object,key){const value=object[key];const input=document.createElement('input');input.setAttribute('aria-label',key);if(typeof value==='boolean'){input.type='checkbox';input.checked=value;input.onchange=()=>object[key]=input.checked}else{input.type=typeof value==='number'?'number':'text';input.step='any';input.value=Array.isArray(value)||typeof value==='object'?JSON.stringify(value):value??'';input.onchange=()=>{try{object[key]=typeof value==='number'?Number(input.value):typeof value==='object'?JSON.parse(input.value):input.value;input.setCustomValidity('')}catch(e){input.setCustomValidity('Enter valid JSON');input.reportValidity()}}}return input}
function fields(object,keys){const wrap=document.createElement('div');wrap.className='fields';for(const key of keys){const label=document.createElement('label');label.textContent=key.replaceAll('_',' ');label.append(inputFor(object,key));wrap.append(label)}return wrap}
function drawEditor(){$('tabs').replaceChildren();for(const name of Object.keys(sections)){const button=document.createElement('button');button.textContent=name;button.className=name===tab?'active':'';button.onclick=()=>{tab=name;drawEditor()};$('tabs').append(button)}const editor=$('editor');editor.className='';editor.replaceChildren();editor.style.marginTop='18px';const key=sections[tab];if(tab==='General'){editor.append(fields(project,['name','author','description','base_character','model_path','portrait_path','scale','game_model_scale','game_triangle_budget','axis_forward','axis_up','global_pitch_semitones','notes']));return}if(key==='raw'){const area=document.createElement('textarea');area.value=JSON.stringify(project,null,2);area.onchange=()=>{try{project=JSON.parse(area.value);area.setCustomValidity('')}catch(e){area.setCustomValidity(e.message);area.reportValidity()}};editor.append(area);return}let data=project[key]??(key==='stats'||key==='input_bindings'?{}:[]);project[key]=data;if(!Array.isArray(data)){editor.append(fields(data,Object.keys(data)));return}const add=document.createElement('button');add.textContent='Add entry';add.onclick=()=>{const defaults={animations:{name:'New clip',source_action:'',game_animation:'',start_frame:0,end_frame:30,speed:1,loop:false,enabled:true},sounds:{name:'New sound',path:'',kind:'voice',event:'',pitch_semitones:0,gain_db:0,trim_start:0,trim_end:0,loop:false,inherited:false},hitboxes:{move:'',attack_id:0,group_id:0,joint_id:0,start_frame:0,end_frame:1,damage:1,size:100,offset:[0,0,0],angle:45,knockback_scale:100,enabled:true},stages:{name:'New stage',model_path:'',collision_path:'',enabled:true},bone_mappings:{game_id:0,target:'',source:'',enabled:true}};data.push(data.length?structuredClone(data[data.length-1]):defaults[key]||{});if(data.at(-1).uid)data.at(-1).uid=crypto.randomUUID();drawEditor()};editor.append(add);const scroll=document.createElement('div');scroll.className='scroll';const table=document.createElement('table');const keys=[...new Set(data.flatMap(Object.keys))].filter(k=>k!=='preview_frames');const head=document.createElement('tr');for(const k of ['Remove',...keys]){const th=document.createElement('th');th.textContent=k.replaceAll('_',' ');head.append(th)}table.append(head);data.forEach((row,i)=>{const tr=document.createElement('tr');const td=document.createElement('td');const remove=document.createElement('button');remove.textContent='×';remove.setAttribute('aria-label','Remove entry '+(i+1));remove.onclick=()=>{data.splice(i,1);drawEditor()};td.append(remove);tr.append(td);for(const k of keys){const cell=document.createElement('td');cell.append(inputFor(row,k));tr.append(cell)}table.append(tr)});scroll.append(table);editor.append(scroll)}
async function saveProject(rebuild){$('projectstatus').textContent=rebuild?'Converting model…':'Saving…';try{const out=await post('/api/project',{id:active.id,project,convert:rebuild});if(rebuild){merge(out);draw()}$('projectstatus').textContent=rebuild?'Model converted. Save the roster and reopen character select to review it.':'Source project saved.'}catch(e){$('projectstatus').textContent=e.message}}
$('saveproject').onclick=()=>busy($('saveproject'),()=>saveProject(false));$('buildproject').onclick=()=>busy($('buildproject'),()=>saveProject(true));
function showView(name){document.querySelectorAll('.view').forEach(el=>el.classList.toggle('active',el.dataset.view===name));document.querySelectorAll('nav.mode button').forEach(button=>button.classList.toggle('active',button.dataset.view===name));$('save').hidden=name!=='roster'}
document.querySelectorAll('nav.mode button').forEach(button=>button.onclick=()=>showView(button.dataset.view));
fetch('/api/packages').then(r=>r.json()).then(items=>{for(const c of items)packages.set(c.id,c);if(state)draw()}).catch(e=>message(e.message));
fetch('/api/roster').then(r=>r.json()).then(s=>{state=s;normalize();draw()}).catch(e=>message(e.message));
