// Generated by tools/extract_opening_audio.py from US motion scripts.
#pragma once
#include <array>
#include <sagas/FighterDescriptors.hpp>
namespace sagas {
struct BattleMotionSound { unsigned motion, frame, fgm; };
inline void descriptor_read(std::istream& input,BattleMotionSound& value) {
    descriptor_read(input,value.motion);
    descriptor_read(input,value.frame);
    descriptor_read(input,value.fgm);
}

inline const DescriptorTable<BattleMotionSound> battle_motion_sounds{"battle_motion_sounds.tsv","motion\tframe\tfgm",1840};
}
