// Generated by tools/extract_throws.py from US FTThrowHitDesc.
#pragma once
#include <array>
#include <sagas/FighterDescriptors.hpp>
namespace sagas {
struct SourceThrow { int frame,damage,angle,growth,weight,base; };
inline void descriptor_read(std::istream& input,SourceThrow& value) {
    descriptor_read(input,value.frame);
    descriptor_read(input,value.damage);
    descriptor_read(input,value.angle);
    descriptor_read(input,value.growth);
    descriptor_read(input,value.weight);
    descriptor_read(input,value.base);
}

inline const DescriptorTable<std::array<SourceThrow,2>> source_throws{"source_throws.tsv","[0].frame\t[0].damage\t[0].angle\t[0].growth\t[0].weight\t[0].base\t[1].frame\t[1].damage\t[1].angle\t[1].growth\t[1].weight\t[1].base",12};
}
