// Generated by tools/extract_throws.py from US FTThrowHitDesc.
#pragma once
#include <array>
namespace sagas {
struct SourceThrow { int frame,damage,angle,growth,weight,base; };
inline constexpr std::array<std::array<SourceThrow,2>,12> source_throws{{
    {{{14,12,45,70,0,80},{46,16,45,70,0,70}}}, // Luigi
    {{{14,12,45,70,0,80},{46,16,45,70,0,70}}}, // Mario
    {{{18,8,45,80,0,70},{9,18,45,70,0,80}}}, // Donkey
    {{{20,14,45,70,0,80},{30,16,45,70,0,70}}}, // Link
    {{{9,16,40,60,0,90},{9,18,40,60,0,90}}}, // Samus
    {{{20,12,70,50,0,100},{20,16,361,50,0,100}}}, // Captain
    {{{27,16,45,70,0,90},{27,16,45,70,0,90}}}, // Ness
    {{{19,12,45,70,0,80},{19,16,45,70,0,70}}}, // Yoshi
    {{{24,13,70,70,0,100},{24,16,115,70,0,70}}}, // Kirby
    {{{10,12,45,60,0,80},{19,15,45,60,0,80}}}, // Fox
    {{{20,12,45,70,0,80},{34,18,45,80,0,60}}}, // Pikachu
    {{{8,14,90,50,0,90},{24,16,45,70,0,80}}}, // Purin
}};
}
