"""Extract callback-owned audio, sleep and victim throw motions from local US data."""
from pathlib import Path
import csv, json, re
root = Path(__file__).resolve().parents[2]
d = root / 'ssb-decomp-re'
ids = {r['name']: int(r['id']) for r in csv.DictReader((root/'sagas/build/assets/reloc/manifest.tsv').open(), delimiter='\t')}
names = ['Luigi','Mario','Donkey','Link','Samus','Captain','Ness','Yoshi','Kirby','Fox','Pikachu','Purin']
source_order = ['Mario','Fox','Donkey','Samus','Luigi','Link','Yoshi','Captain','Kirby','Pikachu','Purin','Ness']
def enum(label):
    src = (d/'src/ft/ftdef.h').read_text().split('typedef enum '+label)[1].split('}')[0]
    src = re.sub(r'/\*.*?\*/|//[^\n]*', '', src, flags=re.S)
    result = {}; value = -1
    for entry in src.split(','):
        m = re.search(r'(nFT\w+)(?:\s*=\s*(-?\d+|nFT\w+))?',entry)
        if m:
            value = (result[m[2]] if m[2].startswith('nFT') else int(m[2])) if m[2] else value+1
            result[m[1]] = value
    return result
motions, statuses = enum('FTCommonMotion'), enum('FTCommonStatus')
status_motion = dict((int(i),m) for i,m in re.findall(r'// Status (\d+).*?\n\s*\{.*?(nFTCommonMotion\w+)', (d/'src/ft/ftcommon/ftcommonstatus.h').read_text(), re.S))
all_tables = (d/'src/ft/ftdata.c').read_text()
tables = {}
for name in names:
    table = re.search(r'FTMotionDesc dFT'+name+r'MotionDescs\[\]\s*=\s*\{(.*?)\n\};', all_tables, re.S)[1]
    tables[name] = re.findall(r'^\s*(?:\{?\s*&ll(\w+)FileID|\{?\s*0x00000000)\s*,', table,re.M)
def clip(name, status):
    if status == '-1': return 0
    return ids.get(tables[name][motions[status_motion[statuses[status]]]],0)
text = '// Generated by tools/extract_battle_callbacks.py.\n#pragma once\n#include <array>\nnamespace sagas {\n'
text += 'struct ThrownClips { unsigned first, next; };\ninline constexpr ThrownClips thrown_clips[12][12][2] = {\n'
for holder in names:
    src = next((d/'src/relocData').glob('*_'+holder+'Main.c')).read_text()
    table = re.search(r'FTThrownStatus\s+\w+\[54\]\s*=\s*\{(.*?)\};',src,re.S)[1]
    pairs = re.findall(r'\{\s*(-1|nFT\w+)\s*,\s*(nFT\w+)\s*\}',table)
    text += ' { // '+holder+'\n'
    for victim in names:
        rows = pairs[source_order.index(victim)*2:source_order.index(victim)*2+2]
        text += '  {'+','.join('{'+str(clip(victim,a))+','+str(clip(victim,b))+'}' for a,b in rows)+'},\n'
    text += ' },\n'
text += '};\ninline constexpr std::array<unsigned,12> sleep_motions{'+','.join(str(ids[tables[n][motions['nFTCommonMotionFuraSleep']]]) for n in names)+'};\n'
voices = {v['name']:v['idx'] for v in json.loads((d/'build/us/src/audio/fgm.ucd.json').read_text())['entries']}
for name in ['nSYAudioFGMCatch','nSYAudioVoicePublicCheer','nSYAudioVoicePublicAmazed','nSYAudioVoicePublicGaspClap','nSYAudioVoicePublicGaspL']:
    text += 'inline constexpr unsigned '+name+' = '+str(voices[name])+';\n'
text += '}\n'
(root/'sagas/include/sagas/BattleCallbackData.hpp').write_text(text)
