"""Extract timed FGM calls for the cartridge clips used by the opening.

This evaluates source motion-script waits, calls and loops, and ignores
non-audio commands. The checked-in output avoids requiring the decomp at runtime.
"""
import argparse
import csv
import json
import re
from pathlib import Path


def extract(decomp, manifest, battle=False):
    ids = {r['name']: int(r['id']) for r in csv.DictReader(manifest.open(), delimiter='\t')}
    voices = {r['name']: r['idx'] for r in json.loads((decomp/'build/us/src/audio/fgm.ucd.json').read_text())['entries']}
    scripts = {}
    for path in list((decomp/'src/relocData').glob('*MainMotion.c')) + list((decomp/'src/sc/scsubsys').glob('scsubsysdata*.c')):
        lines=[];active=[True]
        for line in path.read_text().splitlines():
            if line.startswith('#if'):active.append(active[-1] and 'REGION_US' in line)
            elif line.startswith('#else') and len(active)>1:active[-1]=active[-2] and not active[-1]
            elif line.startswith('#endif') and len(active)>1:active.pop()
            elif all(active):lines.append(line)
        source = re.sub(r'/\*.*?\*/|//[^\n]*', '', '\n'.join(lines), flags=re.S)
        for name, body in re.findall(r'(\w+)\s*\[\s*\]\s*=\s*\{(.*?)\};', source, re.S):
            scripts[name] = re.findall(r'(ftMotion\w+)\(([^()]*)\)', body)
    desc = (decomp/'src/ft/ftdata.c').read_text()
    mapping = {}
    for clip, script in re.findall(r'\{\s*&ll(\w+)FileID,\s*(\w+),', desc):
        if clip in ids and script in scripts:
            mapping.setdefault(ids[clip], script)
    selected = [606,607,608,942,943,944,1188,1015,1821,1876,1269,1387,779,1957,
                810,806,922,936,958,959,953]
    if battle:
        selected=sorted({value for name,value in ids.items() if re.fullmatch(r'FT(?:Mario|Fox|Donkey|Samus|Luigi|Link|Yoshi|Captain|Kirby|Pikachu|Purin|Ness)Anim.*',name) and value in mapping})
    result = []
    for clip in selected:
        if clip not in mapping:
            raise ValueError(f'No motion script for {clip}')
        name, index, frame = mapping[clip], 0, 0
        stack, loops = [], []
        for _ in range(20000):
            if frame > 320 or index >= len(scripts[name]):
                break
            command, arg = scripts[name][index]
            index += 1
            if command == 'ftMotionCommandEnd' or (battle and command=='ftMotionCommandPauseScript'): break
            if command == 'ftMotionCommandWait': frame += int(arg, 0)
            elif command == 'ftMotionCommandWaitAsync': frame = max(frame, int(arg, 0))
            elif command == 'ftMotionCommandSubroutine':
                stack.append((name,index)); name,index=arg,0
            elif command == 'ftMotionCommandReturn':
                if not stack: break
                name,index=stack.pop()
            elif command == 'ftMotionCommandGoto': name,index=arg,0
            elif command == 'ftMotionCommandLoopBegin': loops.append([name,index,int(arg,0)])
            elif command == 'ftMotionCommandLoopEnd':
                loops[-1][2]-=1
                if loops[-1][2]: name,index=loops[-1][:2]
                else: loops.pop()
            elif command=='ftMotionCommandPlaySmashVoice':
                result.append((clip,frame,4294967295))
            elif command in ('ftMotionPlayFGM','ftMotionPlayVoice','ftMotionCommandPlayFGMStoreInfo'):
                result.append((clip, frame, voices[arg] if arg in voices else int(arg,0)))
    return sorted(set(result))


if __name__ == '__main__':
    parser=argparse.ArgumentParser()
    parser.add_argument('--decomp',type=Path,required=True)
    parser.add_argument('--manifest',type=Path,required=True)
    parser.add_argument('--output',type=Path,required=True)
    parser.add_argument('--battle',action='store_true')
    args=parser.parse_args()
    events=extract(args.decomp,args.manifest,args.battle)
    text='// Generated by tools/extract_opening_audio.py from US motion scripts.\n#pragma once\n#include <array>\nnamespace sagas {\nstruct OpeningMotionSound { unsigned motion, frame, fgm; };\n'
    text+=f'inline constexpr std::array<OpeningMotionSound,{len(events)}> opening_motion_sounds{{{{\n'
    text+=''.join(f'    {{{clip},{frame},{fgm}}},\n' for clip,frame,fgm in events)
    text+='}};\n}\n'
    if args.battle:text=text.replace('OpeningMotionSound','BattleMotionSound').replace('opening_motion_sounds','battle_motion_sounds')
    args.output.write_text(text)
