"""Extract US throw damage and release events; special movement remains runtime-owned."""
from pathlib import Path
import re
root=Path(__file__).resolve().parents[2]
names=['Luigi','Mario','Donkey','Link','Samus','Captain','Ness','Yoshi','Kirby','Fox','Pikachu','Purin']
rows=[]
for name in names:
    path=next((root/'ssb-decomp-re/src/relocData').glob('*_'+('Mario' if name=='Luigi' else name)+'MainMotion.c'))
    lines=[];active=[True]
    for line in path.read_text().splitlines():
        if line.startswith('#if'):active.append(active[-1] and 'REGION_US' in line)
        elif line.startswith('#else'):active[-1]=active[-2] and not active[-1]
        elif line.startswith('#endif'):active.pop()
        elif all(active):lines.append(line)
    source=re.sub(r'/\*.*?\*/|//[^\n]*','','\n'.join(lines),flags=re.S)
    scripts=dict(re.findall(r'(?:ftMotionCommand|u32)\s+(\w+)\[.*?\]\s*=\s*\{(.*?)\};',source,re.S))
    desc=dict(re.findall(r'FTThrowHitDesc\s+(\w+)\[.*?\]\s*=\s*\{\s*\{([^}]+)',source,re.S))
    for direction in ('F','B'):
        suffix='ForwardThrow' if name=='Kirby' and direction=='F' else 'CargoAirThrow_0x0D28' if name=='Donkey' and direction=='F' else 'Throw'+direction
        matches=[v for k,v in scripts.items() if k.endswith('_'+suffix)]
        if not matches:raise ValueError((name,suffix))
        script=matches[0]
        descriptor=re.search(r'ftMotionCommandSetThrow\((?:\(u32\))?(\w+)\)',script).group(1)
        values=[int(x.strip(),0) for x in desc[descriptor].split(',') if x.strip()]
        frame=0;release=-1;loop=[]
        for command,arg in re.findall(r'ftMotionCommand(\w+)\(([^()]*)\)',script):
            if command=='Wait':frame+=int(arg,0)
            elif command=='WaitAsync':frame=max(frame,int(arg,0))
            elif command=='LoopBegin':loop.append((frame,int(arg,0)))
            elif command=='LoopEnd':
                start,count=loop.pop();frame+=(frame-start)*(count-1)
            elif command=='SetFlag2' and int(arg,0)==1:release=frame;break
        # Kirby's forward throw releases through its special landing status.
        rows.append((max(1,frame) if release<0 else release,*values[1:6]))
text='// Generated by tools/extract_throws.py from US FTThrowHitDesc.\n#pragma once\n#include <array>\nnamespace sagas {\nstruct SourceThrow { int frame,damage,angle,growth,weight,base; };\ninline constexpr std::array<std::array<SourceThrow,2>,12> source_throws{{\n'
for i,name in enumerate(names):text+='    {{{'+','.join(map(str,rows[i*2]))+'},{'+','.join(map(str,rows[i*2+1]))+'}}}, // '+name+'\n'
(root/'sagas/include/sagas/FighterThrowData.hpp').write_text(text+'}};\n}\n')
